[package]
name = "among-us"
version = "0.1.0"
authors = ["Sam Kirby <sam.kirby94@hotmail.co.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3"
toml = "0.5"
tracing = "0.1"
tracing-subscriber = "0.2"
twilight-cache-inmemory = { git = "https://github.com/sam-kirby/twilight.git", branch = "fix-emoji-encoding" }
twilight-command-parser = { git = "https://github.com/sam-kirby/twilight.git", branch = "fix-emoji-encoding" }
twilight-embed-builder = { git = "https://github.com/sam-kirby/twilight.git", branch = "fix-emoji-encoding" }
twilight-gateway = { git = "https://github.com/sam-kirby/twilight.git", branch = "fix-emoji-encoding" }
twilight-http = { git = "https://github.com/sam-kirby/twilight.git", branch = "fix-emoji-encoding" }
twilight-mention = { git = "https://github.com/sam-kirby/twilight.git", branch = "fix-emoji-encoding" }
twilight-model = { git = "https://github.com/sam-kirby/twilight.git", branch = "fix-emoji-encoding" }
twilight-standby = { git = "https://github.com/sam-kirby/twilight.git", branch = "fix-emoji-encoding" }
twilight-util = { git = "https://github.com/sam-kirby/twilight.git", branch = "fix-emoji-encoding" }

[dependencies.serde]
version = "1"
features = ["derive"]

[dependencies.tokio]
version = "1"
features = ["full"]
